In [1]:
import pandas as pd
import json
import os

# Check your current working directory
print(os.getcwd())

C:\Users\Chaitanya

In [2]:
#create the sample data

data = {
    'city' : ['Mumbai','Delhi','Pune','Hyderabad'] ,
    'sales' : [100000, 200000, 90000,150000] ,
    'region' : ['West','North','West', 'South'] ,
    'active' : [True , True, False, True]
    
}

df = pd.DataFrame(data)

#write to csv

df.to_csv('sales_data.csv',index = False)
print("CSV written")

# write to json
df.to_json('sales_data.json', orient = 'records' , indent =2)
print('JSON written')

#write to excel
df.to_excel('sales_data.xlsx', index = False , sheet_name = 'Sales')
print('Excel written')

CSV written
JSON written
Excel written

In [3]:
# Read CSV
df_csv = pd.read_csv('sales_data.csv')
print("CSV:")
print(df_csv)
print(df_csv.dtypes)

# Read JSON
df_json = pd.read_json('sales_data.json')
print("\nJSON:")
print(df_json)
print(df_json.dtypes)

# Read Excel
df_excel = pd.read_excel('sales_data.xlsx', sheet_name='Sales')
print("\nExcel:")
print(df_excel)
print(df_excel.dtypes)

CSV:
        city   sales region  active
0     Mumbai  100000   West    True
1      Delhi  200000  North    True
2       Pune   90000   West   False
3  Hyderabad  150000  South    True
city        str
sales     int64
region      str
active     bool
dtype: object

JSON:
        city   sales region  active
0     Mumbai  100000   West    True
1      Delhi  200000  North    True
2       Pune   90000   West   False
3  Hyderabad  150000  South    True
city        str
sales     int64
region      str
active     bool
dtype: object

Excel:
        city   sales region  active
0     Mumbai  100000   West    True
1      Delhi  200000  North    True
2       Pune   90000   West   False
3  Hyderabad  150000  South    True
city        str
sales     int64
region      str
active     bool
dtype: object

In [4]:
# 1. Read only specific columns — don't load what you don't need
df_subset = pd.read_csv('sales_data.csv', usecols=['city', 'sales'])
print(df_subset)

# 2. Skip rows — some CSV files have metadata at the top
df_skip = pd.read_csv('sales_data.csv', skiprows=2)
print(df_skip)

# 3. Read only first N rows — useful for previewing large files
df_head = pd.read_csv('sales_data.csv', nrows=2)
print(df_head)

# 4. Handle missing values — custom null markers
df_na = pd.read_csv('sales_data.csv', na_values=['NA', 'N/A', 'missing', '-'])
print(df_na)

        city   sales
0     Mumbai  100000
1      Delhi  200000
2       Pune   90000
3  Hyderabad  150000
       Delhi  200000  North   True
0       Pune   90000   West  False
1  Hyderabad  150000  South   True
     city   sales region  active
0  Mumbai  100000   West    True
1   Delhi  200000  North    True
        city   sales region  active
0     Mumbai  100000   West    True
1      Delhi  200000  North    True
2       Pune   90000   West   False
3  Hyderabad  150000  South    True

In [5]:
# JSON edge case 1 — nested JSON (common in API responses)
nested = {
    'status': 'success',
    'data': [
        {'city': 'Mumbai', 'sales': 100000},
        {'city': 'Delhi',  'sales': 200000}
    ]
}

# Writing nested JSON
with open('nested.json', 'w') as f:
    json.dump(nested, f, indent=2)

# Reading nested JSON — pd.read_json won't work directly
with open('nested.json', 'r') as f:
    raw = json.load(f)

# Extract the data key first
df_nested = pd.DataFrame(raw['data'])
print(df_nested)

     city   sales
0  Mumbai  100000
1   Delhi  200000

In [6]:
df_nested['status'] = raw['status']

df_nested

     city   sales   status
0  Mumbai  100000  success
1   Delhi  200000  success

In [7]:
#write a multi sheet excel file

with pd.ExcelWriter('multi_sheet.xlsx', engine = 'openpyxl') as writer :
    df.to_excel(writer, sheet_name = 'Sales', index = False)
    df.to_excel(writer, sheet_name = 'Backup', index = False)

print("Multi-Sheet Excel written")

PermissionError: [Errno 13] Permission denied: 'multi_sheet.xlsx'

In [ ]:
df_sales = pd.read_excel('multi_sheet.xlsx', sheet_name = 'Sales')
df_sales

In [ ]:
#Based on the sheet number

df_sales = pd.read_excel('multi_sheet.xlsx', sheet_name = 0)
#df_sales
all_sheets = pd.read_excel('multi_sheet.xlsx', sheet_name = None)
type(all_sheets['Sales'])
type(all_sheets.values())
all_sheets.values()
#type(df_backup)

In [ ]:
all_sheets.items()

In [ ]:
dfs = []
for sheet_name, df_sheet in all_sheets.items():
    df_sheet['sheet'] = sheet_name   # track which sheet each row came from
    dfs.append(df_sheet)

In [ ]:
!pip install pyarrow

In [9]:
# Write to parquet
df.to_parquet('sales_data.parquet', index=False)

# Read from parquet
df_parquet = pd.read_parquet('sales_data.parquet')
print(df_parquet)
print(df_parquet.dtypes)

        city   sales region  active
0     Mumbai  100000   West    True
1      Delhi  200000  North    True
2       Pune   90000   West   False
3  Hyderabad  150000  South    True
city        str
sales     int64
region      str
active     bool
dtype: object

In [41]:
!pip install pyarrow --upgrade

Requirement already satisfied: pyarrow in c:\users\chaitanya\miniconda3\lib\site-packages (25.0.0)

In [8]:
df

        city   sales region  active
0     Mumbai  100000   West    True
1      Delhi  200000  North    True
2       Pune   90000   West   False
3  Hyderabad  150000  South    True

In [10]:
# Create sample multi-level Excel file first
import pandas as pd
from itertools import product

# Build multi-level columns
arrays = [
    ['Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2'],
    ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun']
]
columns = pd.MultiIndex.from_arrays(arrays)

data = [
    [100, 120, 90,  110, 130, 150],
    [200, 180, 220, 190, 210, 240],
    [80,  90,  70,  85,  95,  100]
]

df_multi = pd.DataFrame(data, columns=columns, index=['Mumbai', 'Delhi', 'Pune'])
print(df_multi)

# Write to Excel
df_multi.to_excel('multi_level.xlsx', sheet_name='Quarterly')

         Q1             Q2
        Jan  Feb  Mar  Apr  May  Jun
Mumbai  100  120   90  110  130  150
Delhi   200  180  220  190  210  240
Pune     80   90   70   85   95  100

In [11]:
# Read without handling multi-level
df_read = pd.read_excel('multi_level.xlsx', sheet_name='Quarterly')
print(df_read)
print(df_read.columns.tolist())

  Unnamed: 0   Q1 Unnamed: 2 Unnamed: 3   Q2 Unnamed: 5 Unnamed: 6
0        NaN  Jan        Feb        Mar  Apr        May        Jun
1        NaN  NaN        NaN        NaN  NaN        NaN        NaN
2     Mumbai  100        120         90  110        130        150
3      Delhi  200        180        220  190        210        240
4       Pune   80         90         70   85         95        100
['Unnamed: 0', 'Q1', 'Unnamed: 2', 'Unnamed: 3', 'Q2', 'Unnamed: 5', 'Unnamed: 6']

In [12]:
# Tell pandas — first TWO rows are both headers
df_read = pd.read_excel('multi_level.xlsx',
                        sheet_name='Quarterly',
                        index_col=0,      # first column is the index (city)
                        header=[0, 1])    # rows 0 and 1 are both headers

print(df_read)
print(df_read.columns.tolist())

         Q1             Q2
        Jan  Feb  Mar  Apr  May  Jun
Mumbai  100  120   90  110  130  150
Delhi   200  180  220  190  210  240
Pune     80   90   70   85   95  100
[('Q1', 'Jan'), ('Q1', 'Feb'), ('Q1', 'Mar'), ('Q2', 'Apr'), ('Q2', 'May'), ('Q2', 'Jun')]

In [13]:
# Combine levels into one string — Q1_Jan, Q1_Feb etc
df_read.columns = ['_'.join(col) for col in df_read.columns]
print(df_read.columns.tolist())
# ['Q1_Jan', 'Q1_Feb', 'Q1_Mar', 'Q2_Apr', 'Q2_May', 'Q2_Jun']

print(df_read)

['Q1_Jan', 'Q1_Feb', 'Q1_Mar', 'Q2_Apr', 'Q2_May', 'Q2_Jun']
        Q1_Jan  Q1_Feb  Q1_Mar  Q2_Apr  Q2_May  Q2_Jun
Mumbai     100     120      90     110     130     150
Delhi      200     180     220     190     210     240
Pune        80      90      70      85      95     100

In [14]:
# Reset index first — city is currently the index
df_reset = df_read.reset_index()

# Melt to long format
df_long = pd.melt(
    df_reset,
    id_vars    = 'city',
    value_vars = ['Q1_Jan', 'Q1_Feb', 'Q1_Mar', 'Q2_Apr', 'Q2_May', 'Q2_Jun'],
    var_name   = 'quarter_month',
    value_name = 'sales'
)

print(df_long)

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['city']"

In [15]:
df_reset = df_read.reset_index()
print(df_reset.columns.tolist())
print(df_reset.head())

['index', 'Q1_Jan', 'Q1_Feb', 'Q1_Mar', 'Q2_Apr', 'Q2_May', 'Q2_Jun']
    index  Q1_Jan  Q1_Feb  Q1_Mar  Q2_Apr  Q2_May  Q2_Jun
0  Mumbai     100     120      90     110     130     150
1   Delhi     200     180     220     190     210     240
2    Pune      80      90      70      85      95     100

In [16]:
df_reset = df_reset.rename(columns={'index': 'city'})

In [17]:
df_reset = df_reset.rename(columns={'index': 'city'})

df_long = pd.melt(
    df_reset,
    id_vars    = 'city',
    value_vars = ['Q1_Jan', 'Q1_Feb', 'Q1_Mar',
                  'Q2_Apr', 'Q2_May', 'Q2_Jun'],
    var_name   = 'quarter_month',
    value_name = 'sales'
)

print(df_long)

      city quarter_month  sales
0   Mumbai        Q1_Jan    100
1    Delhi        Q1_Jan    200
2     Pune        Q1_Jan     80
3   Mumbai        Q1_Feb    120
4    Delhi        Q1_Feb    180
5     Pune        Q1_Feb     90
6   Mumbai        Q1_Mar     90
7    Delhi        Q1_Mar    220
8     Pune        Q1_Mar     70
9   Mumbai        Q2_Apr    110
10   Delhi        Q2_Apr    190
11    Pune        Q2_Apr     85
12  Mumbai        Q2_May    130
13   Delhi        Q2_May    210
14    Pune        Q2_May     95
15  Mumbai        Q2_Jun    150
16   Delhi        Q2_Jun    240
17    Pune        Q2_Jun    100

In [18]:
# Without expand
print(df_long['quarter_month'].str.split('_'))

# With expand
print(df_long['quarter_month'].str.split('_', expand=True))

0     [Q1, Jan]
1     [Q1, Jan]
2     [Q1, Jan]
3     [Q1, Feb]
4     [Q1, Feb]
5     [Q1, Feb]
6     [Q1, Mar]
7     [Q1, Mar]
8     [Q1, Mar]
9     [Q2, Apr]
10    [Q2, Apr]
11    [Q2, Apr]
12    [Q2, May]
13    [Q2, May]
14    [Q2, May]
15    [Q2, Jun]
16    [Q2, Jun]
17    [Q2, Jun]
Name: quarter_month, dtype: object
     0    1
0   Q1  Jan
1   Q1  Jan
2   Q1  Jan
3   Q1  Feb
4   Q1  Feb
5   Q1  Feb
6   Q1  Mar
7   Q1  Mar
8   Q1  Mar
9   Q2  Apr
10  Q2  Apr
11  Q2  Apr
12  Q2  May
13  Q2  May
14  Q2  May
15  Q2  Jun
16  Q2  Jun
17  Q2  Jun

In [19]:
df_long[['quarter', 'month']] = df_long['quarter_month'].str.split('_', expand=True)
df_long.drop(columns='quarter_month', inplace=True)
print(df_long)

      city  sales quarter month
0   Mumbai    100      Q1   Jan
1    Delhi    200      Q1   Jan
2     Pune     80      Q1   Jan
3   Mumbai    120      Q1   Feb
4    Delhi    180      Q1   Feb
5     Pune     90      Q1   Feb
6   Mumbai     90      Q1   Mar
7    Delhi    220      Q1   Mar
8     Pune     70      Q1   Mar
9   Mumbai    110      Q2   Apr
10   Delhi    190      Q2   Apr
11    Pune     85      Q2   Apr
12  Mumbai    130      Q2   May
13   Delhi    210      Q2   May
14    Pune     95      Q2   May
15  Mumbai    150      Q2   Jun
16   Delhi    240      Q2   Jun
17    Pune    100      Q2   Jun